### ISSUE TITLE
Numpy 2.0 - breaking changes

### ISSUE THREAD

**Issue by PeterMocary** [tfiedor/perun#203]
With the release of NumPy 2.0 (16.6.2024), there are several breaking changes that need to be addressed. Since the migration might require some time, we should limit the version (``numpy>=1.24, <2.0``) for the time being.

Useful links:
- [NumPy 2.0 release notes](https://numpy.org/doc/stable/release/2.0.0-notes.html)
- [Numpy 2.0 migration guide](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html)

Triggered for example here:
```
Traceback (most recent call last):
[...]
File "[...]/perun/postprocess/regressogram/methods.py", line 12, in <module>
    import numpy.lib.histograms as numpy_bucket_selectors
ModuleNotFoundError: No module named 'numpy.lib.histograms'

---- Interactive python interpreter ----
Python 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy.lib.histograms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy.lib.histograms'
>>> import numpy
>>> numpy.lib.histograms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib64/python3.11/site-packages/numpy/lib/__init__.py", line 77, in __getattr__
    raise AttributeError(
AttributeError: numpy.lib.histograms is now private. If you are using a public function, it should be available 
in the main numpy namespace, otherwise check the NumPy 2.0 migration guide.
```

**Comment by PeterMocary** [comment]
Temporary fix merged in PR #205.
